// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TurkcellBank.Infrastructure.Persistence;

#nullable disable

namespace TurkcellBank.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701094000_AddCreditCardPhaseTwo")]
    public partial class AddCreditCardPhaseTwo
    {
    }
}
